name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "bradjste@gmail.com"
        git config --global user.name "bradjste"
        git remote set-url origin https://bradjste:860317b454c05a1b6c2aff7931d878aa0bad6b53@github.com/bradjste/reactp5-website.git
        npm run deploy
